name: Build app distributions
on:
  push:
    tags: '**'

jobs:
  build:
    permissions: 
      contents: read
    strategy:
      matrix:
        os: [ macos-13, windows-2019, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.os == 'macos-13' }}
        name: Install `dmg-license`
        run: npm install dmg-license
      - name: Build the artifact
        run: npm run dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/
          name: ${{ matrix.os }}-dist
          if-no-files-found: error
