name: Build app distributions
on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ macos-14, windows-2022, ubuntu-22.04 ]   # обновлённые версии
    runs-on: ${{ matrix.os }}
    env:
      ARTIFACT_GLOB: dist/${{ matrix.os == 'macos-14' && '*.dmg' || matrix.os == 'windows-2022' && '*.exe' || matrix.os == 'ubuntu-22.04' && '*.AppImage' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - if: ${{ matrix.os == 'macos-14' }}
        name: Install `dmg-license`
        run: npm install dmg-license
      - name: Build the artifact
        run: npm run dist
      - name: Add OS and arch to files
        shell: bash
        run: |-
          I=$(ls -1 ${{ env.ARTIFACT_GLOB }} | head -n1)
          mv "$I" "${I%.*}-${{ runner.os }}-${{ runner.arch }}.${I##*.}"
      - name: Upload built artifact
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: ${{ env.ARTIFACT_GLOB }}
