name: Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      ARTIFACT_GLOB: dist/${{ startsWith(matrix.os, 'macos') && '*.dmg' || startsWith(matrix.os, 'windows') && '*.exe' || startsWith(matrix.os, 'ubuntu') && '*.AppImage' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/setup@v2
        with:
          version: ^12.0.0
          runtime: node@24
          cache: true
          install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - if: ${{ startsWith(matrix.os, 'macos') }}
        name: Install `dmg-license`
        run: pnpm add dmg-license

      - name: Build the artifact
        run: pnpm run dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.ARTIFACT_GLOB }}
          archive: false

  publish:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Fetch build artifacts
        uses: actions/download-artifact@v8
        with:
          skip-decompress: true
          merge-multiple: true
          path: ./dist

      - name: Upload artifacts to the release
        uses: softprops/action-gh-release@v3
        with:
          files: "dist/*"
